---
# Run this playbook on UBUNTU and REDHAT machines to install webserver. 
- hosts: all
  become: yes
  tasks: 
   - name: "Install Webserver on Ubuntu machines"
     apt: 
      name: apache2
      state: present
     when: ansible_os_family=="Debian"

   - name: "Start Webserver on Ubuntu machines"
     service: 
      name: apache2
      state: started
     when: ansible_os_family=="Debian"

   - name: "Install Webserver on Redhat machines"
     dnf: 
      name: httpd
      state: present
     when: ansible_os_family=="RedHat"

   - name: "Start Webserver on Ubuntu machines"
     service: 
      name: httpd
      state: started
     when: ansible_os_family=="RedHat"
